### PR TITLE
Feature/skip unexpected tlv tags

### PR DESCRIPTION
**Pull request by milandaji**
Feature/skip unexpected tlv tags

### CODE REVIEW

**Review by dgago — APPROVED** [review]

**Comment by adamdecaf** [comment]
👋  Thanks for using this library. I was curious if the recent changes on moov-io/iso8583 have solved all the issues on this fork. If not we'd like to know what they are and work to resolve them.

**Comment by milandaji** [comment]
Hi @adamdecaf. We still have one issue left, I think @FacundoMora is working on it. I don't have the details of it, @FacundoMora can you help us with that 😄 ?

**Comment by FacundoMora** [comment]
Hi @adamdecaf, we have on the pendings create a PR adding composites with bitmaps implementation, I talked to Pavel about this and he was good about it.
The idea is to be able to configure an arbitrary sized bitmap (This feature was added some releases ago in your repo) to a composite, this means that some fields have a private bitmap for themself to check the existence of their subfields.
I'll be in touch with you when I have this implementation ready, thanks!

**Comment by adamdecaf** [comment]
Sounds good, thanks!

**Pull request merged**
